### ISSUE TITLE
MC 1.16.4 fabric can't use it

### ISSUE THREAD

**Issue by Kogasa-touhou** [OKTW-Network/FabricProxy#11]
[10:07:52 ERROR]: [cengjingdexuan|/183.213.241.56:2036] <-> ServerConnector [SURVIVAL] - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!
19c7017b227472616e736c617465223a

FabricProxy 1.4

**Comment by james58899** [comment]
v1.3.3 is compatible with Minecraft 1.16.4

**Comment by Kogasa-touhou** [comment]
1.3.3 the same error

**Comment by Kogasa-touhou** [comment]
Latest log with 1.4.0
[00:06:01] [main/INFO]: Loading for game Minecraft 1.16.4
[00:06:01] [main/INFO]: [FabricLoader] Loading 44 mods: fabric-screen-handler-api-v1@1.1.0+872498413a, fabricproxy@1.4.0, minecraft@1.16.4, fabric-renderer-api-v1@0.3.3+a4467d2a3a, fabric-networking-blockentity-v0@0.2.5+b50ffc7b3a, fabric-keybindings-v0@0.2.0+3fa9f7c53a, fabric-command-api-v1@1.0.9+a4467d2a3a, fabricloader@0.10.6+build.214, fabric-tool-attribute-api-v1@1.2.5+c93221003a, fabric-renderer-indigo@0.4.3+a4467d2a3a, fabric-structure-api-v1@1.1.0+f8ac1db23a, fabric-containers-v0@0.1.8+045df74f3a, fabric-object-builder-api-v1@1.9.2+a89534ab3a, fabric-item-api-v1@1.2.0+f8ac1db23a, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, fabric-events-interaction-v0@0.4.1+f8ac1db23a, fabric-game-rule-api-v1@1.0.3+a4467d2a3a, fabric-api-base@0.2.0+9f0fb4b83a, fabric-rendering-v0@1.1.1+f8ac1db23a, fabric-rendering-v1@1.3.1+f8ac1db23a, fabric-key-binding-api-v1@1.0.1+730711c63a, fabric-rendering-data-attachment-v1@0.1.4+f8ac1db23a, autoconfig1u@3.3.1, fabric-resource-loader-v0@0.3.1+facf3bbf3a, fabric-textures-v0@1.0.5+a4467d2a3a, fabric-content-registries-v0@0.1.9+059ea8663a, fabric-tag-extensions-v0@1.0.3+ac8e8c593a, fabric-biome-api-v1@3.0.0+8367596d3a, fabric-rendering-fluids-v1@0.1.12+f8ac1db23a, fabric-registry-sync-v0@0.6.1+a4467d2a3a, fabric-commands-v0@0.2.0+52d308363a, fabric-blockrenderlayer-v1@1.1.4+c6a8ea893a, fabric-lifecycle-events-v1@1.2.0+74cc3b203a, fabric-mining-levels-v0@0.1.2+b764ce993a, fabric-renderer-registries-v1@2.2.0+f8ac1db23a, fabric-loot-tables-v1@1.0.1+432ea1883a, fabric-events-lifecycle-v0@0.2.0+16acbe5b3a, fabric@0.25.4+1.16, carpet@1.4.16, fabric-particles-v1@0.2.2+fb0d9b0e3a, fabric-models-v0@0.1.1+f8ac1db23a, fabric-item-groups-v0@0.2.1+a4467d2a3a, fabric-object-builders-v0@0.7.1+a4467d2a3a, fabric-networking-v0@0.1.10+e00ecb5f3a
[00:06:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/D:/MCSManager_8.6.11_Win_x86/server/server_core/1_16_3/server/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[00:06:07] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:06:07] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[00:06:07] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[00:06:07] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[00:06:07] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[00:06:07] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[00:06:08] [main/INFO]: Reloading ResourceManager: Default, bukkit, Fabric Tool Attribute API (v1)
[00:06:09] [Worker-Main-8/INFO]: Loaded 7 recipes
[00:06:09] [Worker-Main-8/INFO]: Loaded 927 advancements
[00:06:10] [main/INFO]: Applied 0 biome modifications to 0 of 79 new biomes in 1.781 ms
[00:06:10] [Server thread/INFO]: Starting minecraft server version 1.16.4
[00:06:10] [Server thread/INFO]: Loading properties
[00:06:10] [Server thread/INFO]: Default game type: SURVIVAL
[00:06:10] [Server thread/INFO]: Generating keypair
[00:06:10] [Server thread/INFO]: Starting Minecraft server on *:31001
[00:06:10] [Server thread/INFO]: Using default channel type
[00:06:10] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[00:06:10] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[00:06:10] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[00:06:10] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[00:06:10] [Server thread/INFO]: Preparing level "world"
[00:06:10] [Server thread/INFO]: [CM]: loaded setting carpets as true from carpet.conf
[00:06:10] [Server thread/INFO]: [CM]: loaded setting onePlayerSleeping as true from carpet.conf
[00:06:10] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[00:06:12] [Server thread/INFO]: Preparing spawn area: 0%
[00:06:12] [Server thread/INFO]: Preparing spawn area: 0%
[00:06:12] [Server thread/INFO]: Preparing spawn area: 0%
[00:06:12] [Server thread/INFO]: Preparing spawn area: 0%
[00:06:13] [Server thread/INFO]: Time elapsed: 2474 ms
[00:06:13] [Server thread/INFO]: Done (2.667s)! For help, type "help"
ive Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1:                                                
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:140) ~[50eef41e-e3f0-4eed-9468-6a1e13912751.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:107) ~[50eef41e-e3f0-4eed-9468-6a1e13912751.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:72) ~[50eef41e-e3f0-4eed-9468-6a1e13912751.jar:?]
	... 27 more
[00:06:03] [main/WARN]: Failed to select mixin config: velocity.mixins.json
java.lang.RuntimeException: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1:                                                
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:74) ~[50eef41e-e3f0-4eed-9468-6a1e13912751.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.serializer.Toml4jConfigSerializer.deserialize(Toml4jConfigSerializer.java:55) ~[50eef41e-e3f0-4eed-9468-6a1e13912751.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.ConfigManager.load(ConfigManager.java:87) ~[50eef41e-e3f0-4eed-9468-6a1e13912751.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.ConfigManager.<init>(ConfigManager.java:53) ~[50eef41e-e3f0-4eed-9468-6a1e13912751.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.register(AutoConfig.java:45) ~[50eef41e-e3f0-4eed-9468-6a1e13912751.jar:?]
	at one.oktw.FabricProxy.onLoad(FabricProxy.java:21) ~[FabricProxy-1.4.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:599) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:475) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:437) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_271]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:222) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1:                                                
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:140) ~[50eef41e-e3f0-4eed-9468-6a1e13912751.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:107) ~[50eef41e-e3f0-4eed-9468-6a1e13912751.jar:?]
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:72) ~[50eef41e-e3f0-4eed-9468-6a1e13912751.jar:?]
	... 27 more

**Comment by james58899** [comment]
Check config, syntax error

**Comment by Kogasa-touhou** [comment]
thanks
