### ISSUE TITLE
Console Spam on Login (Received invalid channel...)

### ISSUE THREAD

**Issue by StormyIceLeopard** [OKTW-Network/FabricProxy#31]
**Describe the bug**
Everytime someone joins, console is spammed.

**Expected behavior**
No console spam.

**FabricProxy.toml**
Provide you config (without secret):
```
BungeeCord = true
BungeeCordWorkaround = true
Velocity = false
allowBypassProxy = false
```

**Versions**
Minecraft version: 1.16.5
FabricProxy version: 1.4.7
Fabric API version: 0.37.0+1.16
Velocity version: N/A
BungeeCord version: Waterfall 1.16 Build 431

**Server log**
Provide any related logs on the server side:
```
[09:34:13] [User Authenticator #1/INFO]: [Bukkit|ServerLoginNetworkHandler] UUID of player StormyIceLeopard is b6d2ea2a-0ea9-4d5c-bbb4-89894e0188d5
[09:34:14] [Server thread/INFO]: StormyIceLeopard[/{IP REDACTED}:35904] logged in with entity id 152 at (122.5, 74.0, 214.5)
[09:34:14] [Netty Epoll Server IO #1/WARN]: [ServerPlayNetworkAddon for StormyIceLeopard] Received invalid channel identifier "legacy:fml|hs" from connection net.minecraft.class_2535@3b2d08de
net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: legacy:fml|hs
	at net.minecraft.class_2960.<init>(class_2960.java:41) ~[intermediary-server.jar:?]
	at net.minecraft.class_2960.<init>(class_2960.java:46) ~[intermediary-server.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.addId(AbstractChanneledNetworkAddon.java:198) ~[cb23cb27-2104-4ed9-9841-40f736453e6f.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.receiveRegistration(AbstractChanneledNetworkAddon.java:152) ~[cb23cb27-2104-4ed9-9841-40f736453e6f.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:82) ~[cb23cb27-2104-4ed9-9841-40f736453e6f.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:84) ~[cb23cb27-2104-4ed9-9841-40f736453e6f.jar:?]
	at net.minecraft.class_3244.handler$zho000$handleCustomPayloadReceivedAsync(class_3244.java:2840) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12075(class_3244.java) ~[intermediary-server.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:44) ~[intermediary-server.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:9) ~[intermediary-server.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:156) ~[intermediary-server.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:147) ~[intermediary-server.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:52) ~[intermediary-server.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[intermediary-server.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[intermediary-server.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[intermediary-server.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[intermediary-server.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[intermediary-server.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[intermediary-server.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[intermediary-server.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[intermediary-server.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[intermediary-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[intermediary-server.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[intermediary-server.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[intermediary-server.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[intermediary-server.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[intermediary-server.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Proxy log**
Provide any related logs on the proxy side:
```
N/A
```

**Additional context**
N/A

**Comment by samuelh2005** [comment]
It looks like the server your connecting to is Forge, before 1.13.
Or your Minecraft client might be,
